In [1]:
 # Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

In [2]:
#Load the CSV Output File From Part 1 Into This File
file = "Weather_Output.csv"
weather_output_df = pd.read_csv(file)
weather_output_df

,Unnamed: 0,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
0,0,Cabo San Lucas,5,MX,1583125502,43,22.89,-109.91,71.60,8.05
1,1,Santa Vitória do Palmar,4,BR,1583125681,89,-33.52,-53.37,67.39,9.13
2,2,Mehamn,97,NO,1583125384,78,71.04,27.85,24.80,9.17
3,3,Mar del Plata,0,AR,1583125447,88,-38.00,-57.56,72.00,13.87
4,4,Flin Flon,69,CA,1583125681,95,54.77,-101.86,-1.08,5.37
...,...,...,...,...,...,...,...,...,...,...
498,498,Toamasina,40,MG,1583125734,83,-18.17,49.38,77.00,10.29
499,499,Tres Arroyos,1,AR,1583125734,29,-38.37,-60.28,75.45,12.39
500,500,Gorontalo,98,ID,1583125520,92,0.54,123.06,78.12,5.10
501,501,Port Blair,14,IN,1583125490,69,11.67,92.75,81.18,9.04
502,502,Tessalit,0,ML,1583125505,11,20.20,1.01,66.87,9.78

In [3]:
#Create the Humidity Heatmap

#Configure the GMaps API Key
gmaps.configure(g_key)

#Plot the HeatMap
#Code Found from APIs Day 3 Activity 7
fig =gmaps.figure(map_type = "ROADMAP")

#Specify the Locations
locations = weather_output_df[['Lat','Lng']]

#Specify the Weights
humidity = weather_output_df['Humidity'].astype(float)

#Create the Heatmap Layer
heat_layer = gmaps.heatmap_layer(locations, weights = humidity, dissipating = False, max_intensity = 10, point_radius = 3)

#Append the Heatmap Layer to the Heatmap
fig.add_layer(heat_layer)

#Display the Heatmap
fig

Figure(layout=FigureLayout(height='420px'))

In [4]:
#Create a DataFrame of Ideal Cities to Visit Based on Weather Criteria

#Define Desired Temperature Range
min_temp = 60
max_temp = 70

#Define the Desired Humidity Range
min_humid = 0
max_humid = 30

#Define the Desired Cloudiness Range
min_cloud = 20
max_cloud = 40

#Define the Desired Wind Speed Range
min_wind = 5
max_wind = 10

#Create the DataFrame of Ideal Cities
ideal_cities = weather_output_df.loc[(weather_output_df['Max Temp']>min_temp) &
                                     (weather_output_df['Max Temp']<max_temp) &
                                     (weather_output_df['Humidity']>min_humid) &
                                     (weather_output_df['Humidity']<max_humid) &
                                     (weather_output_df['Cloudiness']>min_cloud) &
                                     (weather_output_df['Cloudiness']<max_cloud) &
                                     (weather_output_df['Wind Speed']>min_wind) &
                                     (weather_output_df['Wind Speed']<max_wind)]
ideal_cities = ideal_cities.reset_index(drop=True)
ideal_cities

,Unnamed: 0,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
0,224,Gaoua,25,BF,1583125701,16,10.30,-3.25,68.88,5.46
1,248,Atar,26,MR,1583125708,17,20.52,-13.05,65.01,9.40

In [9]:
#Use the Google Places API to Find the First Hotel for Each City Located 5000 Meters of Your Coordinates

#Create an Empty DataFrame to Assign the Hotels
#ideal_cities['Hotels'] = ""

#Iterate Through Rows to Find the First Hotel for Each City Located 5000 Meters of The Coordinates
for index, rows in ideal_cities.iterrows():
    #Create a Location Parameter
    location = ideal_cities[['Lat', 'Lng']]
    #Create the URL
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    params = {"type":"lodging", "key":g_key, "radius":5000, "location":location}
    url = requests.get(base_url, params = params)
    response = url.json()
    print(response)

{'html_attributions': [], 'results': [], 'status': 'INVALID_REQUEST'}
{'html_attributions': [], 'results': [], 'status': 'INVALID_REQUEST'}